- Gruntfile.js
- samples/DynamicArea.html
- src/js/idd.area.js
- src/js/idd.base.js
Declarative attribute: `data-idd-plot="area"`.
Imperative call: `chart.area(name,{x:x, y1:upper_area_boundary, y2:lower_area_boundary, fill: color})`
> Area: new standard idd plot type

- src/idd/idd.base.js
- tsd.json
Added ability to set anchor for DOM plot.
> Anchor added to set method in DOMPlot

- src/idd/idd.base.js
> issue 36 fix

- src/viewer/Band.ts
- src/viewer/ChartViewer.ts
- src/viewer/ChartViewerControl.ts
- src/viewer/Fallback.ts
- src/viewer/Heatmap.ts
- src/viewer/Line.ts
- src/viewer/Markers.ts
- src/viewer/Plot.ts
- src/viewer/PlotList.ts
- src/viewer/PlotViewer.ts
fixes #38 .
@ElenaPochernina check any other files you are going to add for correct latter case in references.
> fixing latter case in references to TS files

- src/idd/idd.markers.uncertain.js
- test/manual/Boxwhisker plot.html
- test/manual/mainGlobal.js
> Boxwhisker instead of 3 different shapes

- samples/Nested charts.html
- src/css/idd.css
- src/idd/idd.base.js
- src/idd/idd.formatter.js
- src/idd/idd.heatmap.js
- src/idd/idd.utils.js
> Fix samles with Dom markers and Nested Chart. Fix formatters

- Gruntfile.js
- src/idd/idd.ko.js
- src/idd/wrapper_footer_knockout.txt
- src/idd/wrapper_header_knockout.txt
* idd.ko.js file
* adding building separate output file idd_knockout.js with knockout bindings
> idd knockout initial support

- all-samples.html
- index.html
- sample-bubbles.html
- sample-geoheatmap.html
> Update samples. Add mercator transform in geo-heatmap sample

- src/css/idd.css
> fix bug 67 with cursor in Chrome

- src/css/chartViewer.css
- src/css/idd.css
- src/idd/idd.chart.js
- src/idd/idd.figure.js
- src/viewer/PlotViewer.ts
- src/viewer/chartViewer.d.ts
Export to SVG text labels from left, right, top and bottom around Plot (include axis titles and title of plot).
issue #83 
issue #78
> Text labels

- src/css/idd.css
- src/idd/idd.heatmap.js
- src/idd/idd.markers.uncertain.js
- src/viewer/PlotViewer.ts
> Fix bug with probes. Add bounding-box to box&whisker markers

- Gruntfile.js
- RELEASE_NOTES.md
- src/idd/idd.ko.labels.js
- src/idd/wrapper_footer_knockout.txt
+ reducing duplicate file listing in gruntfile.js
> Knockout bindings for the label plot

- src/idd/idd.base.js
- src/idd/idd.bingmapsplot.js
Fix bug: At the initial moment Bing map and heatmap had different zoom level .
> fix heatmap on map initial state

- package.json
- src/idd/idd.figure.js
> fix bug 95 (the x-axis label is shifted down in the exported svg)

- IDDSamples.html
- samples/KO.Markers.html
- src/idd/idd.ko.markers.js
Sample that demonstrates ability to control properties of markers with Knockout.
> KO markers sample

- bower.json
> fixing link to svg.js

- IDDSamples.html
- samples/KO.Bars.html
- src/idd/idd.ko.markers.js
including KO boxplot markers fix
> Ko bars sample

- samples/KO.UncertaintyMarkers.html
- src/idd/idd.axis.js
- src/idd/idd.ko.markers.js
- src/idd/idd.markers.uncertain.js
- test/manual/Boxwhisker plot.html
- test/manual/mainGlobal.js
> Add property thickness to box whisker. Labelled axis (fixed export to svg).

- src/idd/idd.base.js
- src/idd/idd.ko.markers.js
- src/idd/idd.markers.uncertain.js
1. add horizontal bars (add property `orientation`)
2. fixed bug (export bars to svg)
3. add property `padding` in plot
> Add horizontal bars

- samples/ChangeBottomAxisLabelsAngle.html
- src/idd/idd.axis.js
- test/manual/mainGlobal.js
add sample `ChangeBottomAxisLabelsAngle.html`
fix property rotateAngle to use it without Knockout
> Add sample

- bower.json
Fixing bower link to FileSaver
> FileSaver bower fix

- .npmignore
- package.json
Updated File Saver library access in package.json, other small changes for npm
> updated files for npm publishing

- RELEASE_NOTES.md
- package.json
- samples/Bar chart.html
- samples/KO.LogTransform.html
- src/idd/idd.ko.js
added iddXAxisSettings, iddYAxisSettings bindings
> iddXAxisSettings, iddYAxisSettings bindings

- RELEASE_NOTES.md
- samples/PolylineInFigure.html
- src/idd/idd.figure.js
Added data-idd-navigation attribute to the figure element to enable navigation on the central part of the figure
> data-idd-navigation attribute

- src/idd/idd.subplots.js
Plots, axes, plot titles, axes titles in subplots can be exported to a valid SVG file
> Subplots to SVG

- samples/Subplots.html
- samples/SubplotsCommonVisibility.html
- samples/SubplotsMargin.html
- samples/SubplotsVisualRectBinding.html
- src/css/idd.css
- src/idd/idd.subplots.js
added functionality via data-idd-horizontal-binding, data-idd-vertical-binding attributes
> Axes binding in Subplots

- Gruntfile.js
- RELEASE_NOTES.md
- package.json
- samples/KO.BoundaryLine.html
- samples/KO.BoundaryLineForeachBinding.html
- samples/KO.BoundaryLineStyledForeach.html
- samples/KO.Polyline.html
- src/idd/idd.base.js
- src/idd/idd.ko.boundaryLine.js
- src/idd/idd.utils.js
Added Boundary line plot. Behaves a bit like axes, though not  quite. 
a) Infinite vertical or horizonal line with specified X or Y coordinate that spans the entire plot and does not appear in a legend.
b) Boundary line can also have a label, which is drawn alongside it in appropriate direction (vertical or horizontal), but not ticks (sample page KO.BoundaryLine.html).
c) There can be any number of boundary lines for one plot. Such functionality can be implemented using Foreach KO binding (see KO.BoundaryLineForeachBinding.html)
d) Boundary lines are exportable to SVG.
e) Boundary lines can be style via iddStroke, iddThickness and iddLineDash bindings (sample page KO.BoundaryLineStyledForeach.html)
> Boundary line plot

- RELEASE_NOTES.md
- package.json
- src/idd/idd.base.js
- src/idd/idd.heatmap.js
- test/exportSvgTest.js
- yarn.lock
- Master plot got new 'initialized' property (jQuery Promise) which provides the way to use the plot after it is fully initialized.
- Updated dependencies: grunt, grunt-contrib-concat, grunt-contrib-copy, grunt-contrib-jasmine, grunt-contrib-uglify, grunt-ts
> Updated 'grunt-' dependencies, added 'initialized' promise to master plot 

- src/idd/idd.animation.js
- src/idd/idd.navigation.js
I'm having problems with using IDD with Webpack in production mode. It seems that it's getting read as if it was in strict mode. I've added a few variable declarations, to get rid of several exceptions caused by this. I'm not sure this is all of them, though.
> Added declarations for some undeclared variables.

- .drone.yml
- README.md
* Signing the drone.io build pipieline
* Build badge now points to drone
> Signing the build & badge update
